# Setup
title:               'Слоноблок'
tagline:             'Екоощадне будівництво'
description:         'Великі будівельні блоки для екоощадного будівництва.'
url:                 https://slonoblock.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Володимир Лісівка
  email:             slonoblock@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
#google_analytics_id: 
